#!/usr/bin/env bash

. gobin
. goroot
. goversion

require_cmd "$GC"
require_cmd "$MK"

SOURCE="$*"
TARGET="/dev/null"

set -e

if [[ -n "$TM_PROJECT_DIRECTORY" ]]; then
	"$MK" -C "$TM_PROJECT_DIRECTORY"
elif [[ -n "$TM_DIRECTORY" ]]; then
	"$MK" -C "$TM_DIRECTORY"
else
	"$GC" -o "$TARGET" "$SOURCE" 1>&2
fi
echo "Build succeeded."
