#!/usr/bin/env bash
. "$TM_SUPPORT_PATH/lib/bash_init.sh"

. gobin
. goversion

require_cmd "$GC"
require_cmd "$AR"

TMPDIR="`mktemp -d -t gopack`"
trap "rm -rf '$TMPDIR'" EXIT

BASENAME="`basename -- "$*" .go`"
SOURCE="$*"
TARGET="$TMPDIR/$BASENAME.a"
OBJECT="$TMPDIR/$BASENAME.$O"

set -e

"$GC" -o "$OBJECT" "$SOURCE" 1>&2
"$AR" vgrc "$TARGET" "$OBJECT" | /usr/bin/sed "s|$TMPDIR/*||"
echo "Build succeeded."
